### ISSUE TITLE
Decouple party theme from base app

### ISSUE THREAD

**Issue by SeanMcGrath** [morganecf/jitsi-party#111]
I propose we move sooner rather than later to make the entire "cabin weekend" layer of this a configuration over a jitsi-party platform.

This means having things like welcome screen background/style, avatars, etc. all be optional or otherwise specified completely by config.

Ultimately I think this will result in making this repo a "base" repo and deploying the party app itself from a fork of this which will contain the necessary configs/customizations

**Comment by SeanMcGrath** [comment]
Have made some progress here. Major hurdle is generification of avatars

**Comment by hndrewaall** [comment]
Done
