### ISSUE TITLE
Custom backgrounds for themed rooms

### ISSUE THREAD

**Issue by SeanMcGrath** [morganecf/jitsi-party#35]

**Comment by SeanMcGrath** [comment]
I looked into this and due to CORS it will be a total PITA to be able to modify the actual jitsi iframe from the party webapp consistently, since the two are served from different subdomains right now

**Comment by hndrewaall** [comment]
I'm fine with deprioritizing this until it makes more sense to start building our own jitsi app images, though honestly I don't think it would be that much work to do that

**Comment by SeanMcGrath** [comment]
closing as dupe of https://github.com/morganecf/jitsi-party/issues/6
