### ISSUE TITLE
Map loads very slowly

### ISSUE THREAD

**Issue by dsshimel** [morganecf/jitsi-party#83]
When I click the map button, it takes a really long time to load.

**Comment by dsshimel** [comment]
I wonder if the slowdown is correlated with how many people are using the app at once.

**Comment by SeanMcGrath** [comment]
could not repro

**Comment by dsshimel** [comment]
The map still loads very slowly for me (perhaps not at all?).

**Comment by morganecf** [comment]
FIXED!!!!!!
