### ISSUE TITLE
Error checking for displayName

### ISSUE THREAD

**Issue by morganecf** [morganecf/jitsi-party#9]
Users shouldn't be able to enter a blank name

**Comment by dsshimel** [comment]
Was this fixed by setting minLength="1" on the Welcome page (https://github.com/morganecf/jitsi-party/blob/623a5937b0e9c839769e7200c8ad5ee3dcfe8305/app/client/jsx/Welcome.jsx#L83)?

**Comment by RibhiEl-Zaru** [comment]
Took a look and tested and it seems that on login this is true, but it is still possible through the jitsi settings. Looking into making a PR with a fix.

**Comment by RibhiEl-Zaru** [comment]
Talked with Morg, and we have little/no control over the jitsi settings, but it doesn't really matter cuz it doesn't link with our DB. figure this can be closed.
