### ISSUE TITLE
whats this?

### ISSUE THREAD

**Issue by Fahad-pnw** [morganecf/jitsi-party#93]
are you guys intending to keep this open sourced or its limited preview only? I'd really like to dive in and find out what you guys are working on, may be i could collaborate or help somehow as i'm looking for a party-case for jitsi-meet, any chance you guys could share live-urls ?

**Comment by Fahad-pnw** [comment]
i compiled after pulling a few hair! the work is awesome, wish i too had the access to your jitsi meet server to get some inspiration!

that twitch feed is nice, however, i wonder if you guys would be doing it via jibri, i mean somehow self hosting streams? Hope you guys would be keeping this open but my guess is you'd close-source it very soon..

**Comment by morganecf** [comment]
Hi @Fahad-pnw! We are keeping this open-source. :slightly_smiling_face: We have plans right now to make it fully customizable so that you can specify a configuration for your own party, so stay tuned! While we can't give you access to the server we're using, you can easily use Jitsi's demo client URL instead. Just uncomment this line (make sure to comment out the domain above it): https://github.com/morganecf/jitsi-party/blob/master/app/client/jsx/JitsiVideo.jsx#L119

Please also set `SHOW_JITSI_WATERMARK` to true, since Jitsi asks us to leave the watermark while using their demo service: https://github.com/morganecf/jitsi-party/blob/master/app/client/jsx/JitsiVideo.jsx#L125

**Comment by Fahad-pnw** [comment]
You just made my dayyyyyy!!!!
Will be studying the scripts thoroughly tomorrow. :)

**Comment by hndrewaall** [comment]
Our plan is to keep this customizable and continue to pull out our party-specific stuff to allow easy instantiation of new "houses". In the near term we will continue to focus on our own community, but we def would like this to be a general-purpose, reusable solution for people to build video "spaces" of their own!

**Comment by Fahad-pnw** [comment]
nooo, don't put out party specific stuff lol, i'm trying to build a partying solution as well!

okay, just to understand a bit, why did you guys choose python/flask, i mean since the scripts are itself in react, would it have been better to keep the same base for serving content, that is may be nodejs? 
It does look like you guys are awesome at python, so that must have been the reason?
i'm not that good with python though so i guess i'd have to learn some stuff around your repo, that i'd be doing tonight.

about new "houses" and "spaces", what's that and how's the structure?
after compiling i couldn't look through as much as i was trying to recompile but failed to do so by last night, some webpack issues probably, will be debugging a bit or it could be pycache too, not sure, have to look into it.

did you guys also modify your own version of jitsi? i.e., modifying the UI within jitsi-meet?

again...nice work :)

**Comment by Fahad-pnw** [comment]
also, here, after setting domain to meet.jit.si, it would still load your servers.
while i ran npm install after setting up the script just to make sure any node modules don't start caching it.
i further ran webpack.config.js
ran flask run --debugger
ran update.sh as well

not sure why won't it update.

![image](https://user-images.githubusercontent.com/9507146/81359830-af41d000-90f3-11ea-876c-0e2b29f45195.png)

**Comment by seangibat** [comment]
Did you try disabling the browser cache in the Chrome console or hard reloading (ctrl or cmd + shift + r)?

Also, can you fork the app and commit your changes? Then we could better provide assistance.

**Comment by Fahad-pnw** [comment]
aaaaah! apologies for the noobish issue! that was it, the browser's cache!

**Comment by hndrewaall** [comment]
haha no worries, the caching stuff is ALWAYS throwing us for a loop. Sometimes I think even the force reload isn't enough. I don't believe it til I've tested an incognito window too :)
